"use client";
import { createContext,useContext,useEffect,useMemo,useState } from "react";
export type ChatWallpaper="none"|"black"|"dark-grid"|"aurora"|"nebula"|"blue-glass"|"cyber"|"minimal"|"space"|"abstract"|"matrix"|"grid"|"orbital"|"network"|"custom";
export type ChatAppearance={wallpaper:ChatWallpaper;customImage?:string;dominant:string;accent:string;luminance:number;blur:number;dim:number;contrast:number;vignette:boolean;grain:boolean;motion:boolean;ensureContrast:boolean};
const defaults:ChatAppearance={wallpaper:"black",dominant:"#080808",accent:"#ffffff",luminance:.04,blur:0,dim:62,contrast:100,vignette:true,grain:true,motion:false,ensureContrast:true};
const legacyMap: Record<string, ChatWallpaper> = { "grid": "dark-grid", "network": "matrix", "orbital": "blue-glass" };
const Context=createContext<{appearance:ChatAppearance;update:(patch:Partial<ChatAppearance>)=>void}|null>(null);
export function ChatAppearanceProvider({children}:{children:React.ReactNode}){const[appearance,setAppearance]=useState(defaults);useEffect(()=>{try{const saved=localStorage.getItem("aegis.chat.appearance.v1");if(saved){const parsed=JSON.parse(saved);if(parsed.wallpaper&&legacyMap[parsed.wallpaper])parsed.wallpaper=legacyMap[parsed.wallpaper];setAppearance({...defaults,...parsed})}}catch{}},[]);function update(patch:Partial<ChatAppearance>){setAppearance(current=>{const next={...current,...patch};try{localStorage.setItem("aegis.chat.appearance.v1",JSON.stringify(next))}catch{}return next})}const value=useMemo(()=>({appearance,update}),[appearance]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useChatAppearance(){const value=useContext(Context);if(!value)throw new Error("useChatAppearance requires ChatAppearanceProvider");return value}
export async function prepareWallpaper(file:File):Promise<Pick<ChatAppearance,"customImage"|"dominant"|"accent"|"luminance">>{if(!["image/png","image/jpeg","image/webp"].includes(file.type))throw new Error("Choose a PNG, JPEG or WebP image.");if(file.size>6*1024*1024)throw new Error("Wallpaper images are limited to 6 MB.");const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/bitmap.width,1000/bitmap.height);const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const context=canvas.getContext("2d",{willReadFrequently:true});if(!context)throw new Error("Image processing is unavailable.");context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const sample=context.getImageData(0,0,canvas.width,canvas.height).data;let r=0,g=0,b=0,count=0;const stride=Math.max(4,Math.floor(sample.length/16000/4)*4);for(let index=0;index<sample.length;index+=stride){r+=sample[index];g+=sample[index+1];b+=sample[index+2];count++}r=Math.round(r/count);g=Math.round(g/count);b=Math.round(b/count);const luminance=(.2126*r+.7152*g+.0722*b)/255;const accent=`rgb(${Math.min(255,r+55)} ${Math.min(255,g+55)} ${Math.min(255,b+55)})`;return{customImage:canvas.toDataURL("image/webp",.82),dominant:`rgb(${r} ${g} ${b})`,accent,luminance}}
