"use client";
/* eslint-disable react/no-unescaped-entities */

import Link from "next/link";
import { Cable, ChevronRight, Cloud, Cookie, Database, Eye, Fingerprint, HardDrive, KeyRound, Laptop, LockKeyhole, Mail, Scale, ShieldCheck } from "lucide-react";
import { useState } from "react";
import type { LegalConfig } from "@/lib/legal/schema";
import { LegalReviewNotice } from "./legal-notice";

const scenarios = {
  local: { label: "Local model", icon: Laptop, note: "The request follows the configured local runtime path. A remote custom endpoint is not local merely because it is OpenAI-compatible.", nodes: ["Your prompt", "Aegis API or device bridge", "Configured local runtime", "Answer"] },
  cloud: { label: "Cloud model", icon: Cloud, note: "The prompt and context required for generation are sent to the cloud provider you selected, under that provider's terms.", nodes: ["Your prompt", "Aegis API", "Selected cloud provider", "Answer"] },
  gmail: { label: "Gmail", icon: Mail, note: "Google connection and Gmail permission are separate. Retrieved email data can be sent to the selected model only when a feature actually uses it.", nodes: ["Your prompt", "Explicit Gmail request", "Selected email data", "Selected AI model", "Answer"] },
  drive: { label: "Drive", icon: HardDrive, note: "Aegis requests authorized Drive metadata or content for the selected action; connection alone does not inject every file into chat.", nodes: ["Your prompt", "Explicit Drive request", "Selected file data", "Selected AI model", "Answer"] },
  github: { label: "GitHub", icon: Cable, note: "Repository data depends on an authenticated connector and its scopes. Write actions require a separate, explicit confirmation boundary.", nodes: ["Your prompt", "GitHub connector", "Selected repository data", "Selected AI model", "Answer"] },
} as const;

const policyNav = ["introduction", "operator", "data", "purposes", "legal-bases", "ai-providers", "connected-tools", "local-processing", "sharing", "transfers", "retention", "security", "rights", "children", "cookies", "changes", "contact", "complaints"];

function retention(value: string | null, unit = "") { return value ? `${value}${unit}` : "Not configured for public policy"; }

export function PrivacyExperience({ legal }: { legal: LegalConfig }) {
  const [scenario, setScenario] = useState<keyof typeof scenarios>("local");
  const active = scenarios[scenario];
  const ActiveIcon = active.icon;
  return <main id="main" className="privacy-page public-rich-page">
    <section className="privacy-hero"><div className="privacy-boundary-art" aria-hidden="true"><span /><span /><i /><b><Fingerprint size={42} /></b></div><div className="shell"><span className="eyebrow"><ShieldCheck size={15} /> Privacy · draft policy</span><h1>Clear boundaries.<br /><span className="chrome-text">Real choices.</span></h1><p>Aegis makes it visible when information follows a local runtime path, when it reaches a selected provider and when a connected service is involved.</p><div className="privacy-hero-actions"><a className="button button-primary" href="#data-flow">See where data goes <ChevronRight size={16} /></a><a className="button button-secondary" href="#policy">Read the draft policy</a></div><div className="policy-meta"><span>Policy {legal.policyVersion}</span><span>Last updated {legal.lastUpdated}</span><span>Effective date: not set</span></div></div></section>

    <section className="privacy-principles shell"><article><Laptop size={22} /><span><small>Local</small><h2>Runtime stays explicit.</h2><p>The endpoint you configure defines the practical boundary.</p></span></article><article><Cloud size={22} /><span><small>Cloud</small><h2>Provider stays visible.</h2><p>Cloud requests can transmit prompt and selected context.</p></span></article><article><KeyRound size={22} /><span><small>Permissions</small><h2>Connection is not use.</h2><p>A scope grants capability; an explicit action retrieves data.</p></span></article><article><Eye size={22} /><span><small>Controls</small><h2>Review and revoke.</h2><p>Sessions and connections remain available from the account surfaces.</p></span></article></section>

    <section id="data-flow" className="privacy-flow-section"><div className="shell"><div className="public-section-heading"><span className="eyebrow">Interactive data path</span><h2>See where your data goes.</h2><p>This diagram describes product paths, not real-time network traffic.</p></div><div className="privacy-scenario-layout"><div className="scenario-tabs" role="tablist" aria-label="Data flow scenario">{Object.entries(scenarios).map(([id, item]) => { const Icon = item.icon; return <button key={id} type="button" role="tab" aria-selected={scenario === id} onClick={() => setScenario(id as keyof typeof scenarios)}><Icon size={18} /><span>{item.label}</span></button>; })}</div><div className="scenario-panel" role="tabpanel"><header><span><ActiveIcon size={22} /></span><div><small>Selected path</small><h3>{active.label}</h3></div></header><div className="flow-nodes">{active.nodes.map((node, index) => <div key={node}><span>{node}</span>{index < active.nodes.length - 1 && <i><ChevronRight size={16} /></i>}</div>)}</div><p>{active.note}</p></div></div></div></section>

    <section className="privacy-separation"><div className="shell privacy-separation-grid"><div><span className="eyebrow">Local versus cloud</span><h2>One interface.<br />Different boundaries.</h2></div><div className="boundary-comparison"><article><Laptop size={24} /><h3>Local runtime</h3><p>Prompt → configured local endpoint → response. Your device, runtime and any network endpoint you configured remain part of the trust model.</p></article><article><Cloud size={24} /><h3>Cloud provider</h3><p>Prompt and required context → selected provider → response. The provider's own processing, retention and location terms can apply.</p></article></div></div></section>

    <section id="policy" className="policy-section shell"><aside><strong>Privacy policy</strong>{policyNav.map((item, index) => <a key={item} href={`#${item}`}><span>{String(index + 1).padStart(2, "0")}</span>{item.replaceAll("-", " ")}</a>)}</aside><article className="policy-document"><header><span className="eyebrow"><Scale size={15} /> Draft legal document</span><h2>Privacy policy</h2><p>A structured description of the current Aegis data paths. Missing legal facts remain visibly unconfigured.</p><LegalReviewNotice configured={legal.configured} /></header>
      <section id="introduction"><h3>1. Introduction</h3><p>This draft explains how Aegis may process data through its Web workspace, API, Desktop application, CLI, model providers and connected services. It is not a claim of absolute privacy or audited compliance.</p></section>
      <section id="operator"><h3>2. Who operates Aegis</h3>{legal.configured ? <p>{legal.identity.entityName}, {legal.identity.entityForm}, at {legal.identity.address}. Contact: {legal.identity.email}.</p> : <p><strong>Legal information not configured.</strong> The entity name, legal form, address, registration, publisher and hosting information must be supplied before launch.</p>}</section>
      <section id="data"><h3>3. Data we process</h3><div className="data-category-list">{[
        ["Account", "Email, display name, avatar reference, password hash and linked identities when provided."],
        ["Sessions", "Session token hash, device name derived from user agent, IP address, creation, last-seen and expiry timestamps."],
        ["Conversations", "Prompts, generated responses, chosen provider/model and conversation timestamps."],
        ["Providers", "Provider definition, encrypted credential where configured, model metadata and connection errors."],
        ["Integrations", "Google identity, granted scopes and encrypted tokens; message/file data only when related routes are requested."],
        ["Technical", "Request identifiers, API errors and local diagnostic logs. No analytics SDK was found in the audited Web code."],
      ].map(([title, body]) => <div key={title}><strong>{title}</strong><p>{body}</p></div>)}</div></section>
      <section id="purposes"><h3>4. Why data is used</h3><p>Data supports account access, session security, conversation delivery, selected provider calls, explicitly requested integrations, diagnostics and abuse prevention. Support or analytics processing must not be inferred unless those systems are configured.</p></section>
      <section id="legal-bases"><h3>5. Legal bases</h3><p>The applicable legal basis for account, contract, security, consent and connected-service processing has not been approved. Candidate bases such as contract performance, legitimate interests or consent require legal review per processing activity.</p></section>
      <section id="ai-providers"><h3>6. AI providers</h3><p>When a cloud model is selected, Aegis sends the prompt and required context to that provider. Policies and regions can change; review the provider directly before use.</p><div className="provider-policy-links"><a href="https://www.nvidia.com/en-us/about-nvidia/privacy-center/" target="_blank" rel="noreferrer">NVIDIA privacy center <ChevronRight size={14} /></a><a href="https://openrouter.ai/privacy" target="_blank" rel="noreferrer">OpenRouter privacy policy <ChevronRight size={14} /></a><a href="https://x.ai/legal/privacy" target="_blank" rel="noreferrer">xAI privacy policy <ChevronRight size={14} /></a><a href="https://openai.com/policies/privacy-policy/" target="_blank" rel="noreferrer">OpenAI privacy policy <ChevronRight size={14} /></a><a href="https://www.anthropic.com/legal/privacy" target="_blank" rel="noreferrer">Anthropic privacy policy <ChevronRight size={14} /></a><a href="https://policies.google.com/privacy" target="_blank" rel="noreferrer">Google privacy policy <ChevronRight size={14} /></a></div></section>
      <section id="connected-tools"><h3>7. Connected tools</h3><p>Google Workspace and GitHub access is voluntary and scope-dependent. Connection, permission grant, data retrieval and sending selected context to a model are separate steps. Disconnecting prevents future API use but provider-side revocation may also be necessary.</p></section>
      <section id="local-processing"><h3>8. Local processing</h3><p>Ollama and LM Studio defaults point to loopback addresses. A custom or remote endpoint changes that boundary. Local-model use does not automatically make the Aegis account database or cloud synchronization local.</p></section>
      <section id="sharing"><h3>9. Data sharing</h3><p>Data can reach the infrastructure operating Aegis, the model provider selected for a request and connected services explicitly used. The infrastructure and subprocessor register is not configured for publication.</p></section>
      <section id="transfers"><h3>10. International transfers</h3><p>No “no transfer” claim is made. Hosting, AI providers, email, monitoring and connected services require an audited location and transfer-mechanism register before launch.</p></section>
      <section id="retention"><h3>11. Retention</h3><div className="retention-register"><div><span>Account</span><strong>{retention(legal.retention.account)}</strong></div><div><span>Sessions</span><strong>{retention(legal.retention.sessions, " days")}</strong></div><div><span>Conversations</span><strong>{retention(legal.retention.conversations)}</strong></div><div><span>Audit logs</span><strong>{retention(legal.retention.auditDays, " days")}</strong></div><div><span>Application logs</span><strong>{retention(legal.retention.logsDays, " days")}</strong></div><div><span>Attachments</span><strong>{retention(legal.retention.attachmentsDays, " days")}</strong></div></div></section>
      <section id="security"><h3>12. Security</h3><p>Observed controls include HttpOnly session cookies, password hashing, encrypted provider/integration secrets where configured, scoped CORS and session revocation. These controls are not a security certification. See the Security page for reporting.</p></section>
      <section id="rights"><h3>13. Your controls and rights</h3><p>Depending on applicable law, rights can include access, correction, deletion, restriction, objection, portability and withdrawal of consent. Their final wording and response process require legal review.</p><div className="rights-actions"><Link href="/account">Correct my profile</Link><Link href="/connections">Manage connections</Link><Link href="/account/security">Review sessions</Link><Link href="/cookies">Manage cookies</Link>{legal.identity.privacyEmail ? <a href={`mailto:${legal.identity.privacyEmail}`}>Contact privacy team</a> : <span>Privacy contact not configured</span>}<span>Data export route not currently available</span></div></section>
      <section id="children"><h3>14. Children</h3><p>Age eligibility and parental-consent rules are not configured. Aegis should not be marketed to children until this section is legally reviewed.</p></section>
      <section id="cookies"><h3>15. Cookies</h3><p>The audited Web/API path uses the strictly necessary `aegis_session` authentication cookie. No analytics or marketing SDK was found, so no consent banner is displayed. See the Cookies page for attributes and future-change requirements.</p></section>
      <section id="changes"><h3>16. Changes</h3><p>Material revisions should update the policy version, effective date and last-updated date. No effective date has been set for this draft.</p></section>
      <section id="contact"><h3>17. Contact</h3><p>{legal.identity.privacyEmail ? <>Privacy: <a href={`mailto:${legal.identity.privacyEmail}`}>{legal.identity.privacyEmail}</a>.</> : "Privacy contact email not configured."} {legal.identity.dpoEmail ? <>DPO: <a href={`mailto:${legal.identity.dpoEmail}`}>{legal.identity.dpoEmail}</a>.</> : "No DPO contact is configured."}</p></section>
      <section id="complaints"><h3>18. Complaints</h3><p>Where data-protection law applies, a person may be entitled to complain to a competent supervisory authority. The correct authority depends on the operator and user's location and must be confirmed after the legal entity is configured.</p></section>
    </article></section>

    <section className="privacy-legal-links"><div className="shell"><div><LockKeyhole size={22} /><span><strong>Legal and security documents</strong><p>Separate routes keep operator identity, terms, cookies, processors and security disclosures reviewable.</p></span></div><nav><Link href="/legal">Legal notice</Link><Link href="/terms">Terms</Link><Link href="/cookies"><Cookie size={15} /> Cookies</Link><Link href="/subprocessors"><Database size={15} /> Subprocessors</Link><Link href="/security"><ShieldCheck size={15} /> Security</Link></nav></div></section>
  </main>;
}
